import re
from typing import Callable, Generator

def generator_numbers(text: str) -> Generator[float, None, None]: #  type Generator[YieldType, SendType, ReturnType].
    """
    Generator that yields floating-point numbers found in the input text.
    Each number is expected to be surrounded by whitespace.
    """
    findings = re.findall(r"\s\d+\.\d+\s", text)
    for val_ in findings:
        yield float(val_)

def sum_profit(text: str, func: Callable) -> float:
    """
    Sums up all floating-point numbers generated by the provided generator function from the input text.
    
    Args:
        text (str): The input text containing floating-point numbers.
        func (Callable): A generator function that yields floating-point numbers from the text.
    
    Usage:
        - total = sum_profit(text, generator_numbers)
        - print(total)  # Outputs the sum of all floating-point numbers in the text.
    """
    total = 0.0
    obj_gen = func(text)
    item = next(obj_gen, None)
    while item is not None:
        total += item
        item = next(obj_gen, None)
    return total